class EleManage(object):  # 注意：字典的键名容易取重复

    def located_by_xpath(self, driver, ele):  # xpath定位
        return driver.find_element_by_xpath(ele)

    def meun_manage(self):   # SaaS菜单
        meun_ele = dict()
        meun_ele['前台功能'] = '//*[@class="menu-wrapper"]/li[1]'
        meun_ele['入场签到'] = '//*[@class="menu-wrapper"]/li[1]/ul/a[1]/li'
        meun_ele['租柜管理'] = '//*[@class="menu-wrapper"]/li[1]/ul/a[2]/li'
        meun_ele['会员办理'] = '//*[@class="menu-wrapper"]/li[1]/ul/a[3]/li'
        meun_ele['会员卡管理'] = '//*[@class="menu-wrapper"]/li[1]/ul/a[4]/li'
        meun_ele['收银台'] = '//*[@class="menu-wrapper"]/li[1]/ul/a[5]/li'

        meun_ele['会籍功能'] = '//*[@class="menu-wrapper"]/li[2]'
        meun_ele['客户管理'] = '//*[@class="menu-wrapper"]/li[2]/ul/a[1]/li'

        meun_ele['教练功能'] = '//*[@class="menu-wrapper"]/li[3]'
        meun_ele['私教课程'] = '//*[@class="menu-wrapper"]/li[3]/ul/a[1]/li'
        meun_ele['私教购买'] = '//*[@class="menu-wrapper"]/li[3]/ul/a[2]/li'
        meun_ele['私教预约'] = '//*[@class="menu-wrapper"]/li[3]/ul/a[3]/li'
        meun_ele['团课管理'] = '//*[@class="menu-wrapper"]/li[3]/ul/a[4]/li'
        meun_ele['公开课管理'] = '//*[@class="menu-wrapper"]/li[3]/ul/a[5]/li'
        meun_ele['体侧报告'] = '//*[@class="menu-wrapper"]/li[3]/ul/a[6]/li'

        meun_ele['店长功能'] = '//*[@class="menu-wrapper"]/li[4]'
        meun_ele['员工管理'] = '//*[@class="menu-wrapper"]/li[4]/ul/a[1]/li'

        meun_ele['高级设置'] = '//*[@class="menu-wrapper"]/li[5]'
        meun_ele['卡种管理'] = '//*[@class="menu-wrapper"]/li[5]/ul/a[1]/li'
        meun_ele['角色管理'] = '//*[@class="menu-wrapper"]/li[5]/ul/a[2]/li'
        meun_ele['文章推送'] = '//*[@class="menu-wrapper"]/li[5]/ul/a[3]/li'
        meun_ele['协议模板'] = '//*[@class="menu-wrapper"]/li[5]/ul/a[4]/li'
        meun_ele['俱乐部信息'] = '//*[@class="menu-wrapper"]/li[5]/ul/a[5]/li'
        return meun_ele

    def register_manage(self):  # 注册
        register_ele = dict()
        register_ele['马上注册按钮'] = '//*[@class="boxce-z"]/span[2]'
        register_ele['登录账号输入框'] = '//*[@class="formbox one"]/div/input'
        register_ele['登录密码输入框'] = '//*[@class="formbox one"]/div[2]/input'
        register_ele['确认密码输入框'] = '//*[@class="formbox one"]/div[3]/input'
        register_ele['场馆名称输入框'] = '//*[@class="formbox one"]/div[4]/input'
        register_ele['地址输入框'] = '//*[@class="formbox one"]/input'
        register_ele['选择城市具体位置'] = '//*[@id="searchResultPanel"]/br[2]'
        register_ele['继续按钮1'] = '//*[@class="buttoncenter"]/button[2]'
        register_ele['法人姓名输入框'] = '//*[@class="formbox tow"]/div/input'
        register_ele['法人手机号输入框'] = '//*[@class="formbox tow"]/div[2]/input'
        register_ele['验证码输入框'] = '//*[@class="formbox tow"]/div[3]/input'
        register_ele['继续按钮2'] = '//*[@class="buttoncenter"]/button[2]'
        register_ele['LOGO上传按钮'] = '//*[@class="changuanimgboxleft"]/div[2]/div[1]'
        register_ele['LOGO上传弹窗按钮'] = '//*[@class="changuanimgboxleft"]/div[2]/div[2]/div[1]/div[2]/div[1]'
        register_ele['LOGO保存按钮'] = '//*[@class="changuanimgboxleft"]/div[2]/div[2]/div[1]/div[2]/div[2]/a[2]'
        register_ele['场馆图片上传按钮'] = '//*[@class="changuanimgboxright"]/div[2]/div[1]'
        register_ele['场馆图片上传弹窗按钮'] = '//*[@class="changuanimgboxright"]/div[2]/div[2]/div[1]/div[2]/div[1]'
        register_ele['场馆图片保存按钮'] = '//*[@class="changuanimgboxright"]/div[2]/div[2]/div[1]/div[2]/div[2]/a[2]'
        register_ele['场馆电话输入框'] = '//*[@class="curbox"]/div[3]/input'
        register_ele['游泳'] = '//div[text()="游泳"]'
        register_ele['跑步'] = '//div[text()="跑步"]'
        register_ele['羽毛球'] = '//div[text()="羽毛球"]'
        register_ele['瑜伽'] = '//div[text()="瑜伽"]'
        register_ele['乒乓球'] = '//div[text()="乒乓球"]'
        register_ele['单车'] = '//div[text()="单车"]'
        register_ele['器械'] = '//div[text()="器械"]'
        register_ele['搏击'] = '//div[text()="搏击"]'
        register_ele['私教'] = '//div[text()="私教"]'
        register_ele['团体操'] = '//div[text()="团体操"]'
        register_ele['完成注册按钮'] = '//*[@class="buttoncenter"]/button[2]'
        return register_ele

    def login_manage(self):  # 登陆
        login_ele = dict()
        login_ele['账号输入框'] = 'username'  # name定位
        login_ele['密码输入框'] = 'password'  # name定位
        login_ele['登录按钮'] = '//span[text()="登录"]'
        return login_ele

    def signin_page(self):  # 入场签到
        signin_ele = dict()
        signin_ele['前台大屏'] = ''
        signin_ele['运动排行'] = ''
        signin_ele['会员办理'] = ''
        signin_ele['潜客登记'] = ''
        signin_ele['潜客登记'] = ''
        signin_ele['姓名'] = ''
        signin_ele['性别选择'] = ''
        signin_ele['性别选择确定'] = ''
        signin_ele['手机号'] = ''
        signin_ele['会籍选择'] = ''
        signin_ele['会籍选择确定'] = ''
        signin_ele['来源选择'] = ''
        signin_ele['来源选择确定'] = ''
        signin_ele['意向选择'] = ''
        signin_ele['意向选择确定'] = ''
        signin_ele['目的选择'] = ''
        signin_ele['目的选择确定'] = ''
        signin_ele['备注'] = ''
        signin_ele['潜客登记提交按钮'] = ''
        signin_ele['会员卡号输入框'] = ''
        signin_ele['会员卡号搜索图标'] = ''
        signin_ele['会员卡号签到按钮'] = ''
        signin_ele['会员卡号签到确定'] = ''
        signin_ele['会员签到-切换条件'] = ''
        signin_ele['会员签到-切换手机号码'] = ''
        signin_ele['会员手机号输入框'] = ''
        signin_ele['会员手机号搜索图标'] = ''
        signin_ele['会员手机号签到按钮'] = ''
        signin_ele['会员手机号签到确定'] = ''
        signin_ele['会员签到-切换会员姓名'] = ''
        signin_ele['会员姓名输入框'] = ''
        signin_ele['会员姓名搜索图标'] = ''
        signin_ele['会员姓名签到按钮'] = ''
        signin_ele['会员姓名签到确定'] = ''
        signin_ele['确认出场按钮'] = ''
        signin_ele['确认出场确定'] = ''
        signin_ele['借出手牌按钮'] = ''
        signin_ele['借出手牌手牌号输入框'] = ''
        signin_ele['借出手牌手牌号搜索图标'] = ''
        signin_ele['借出手牌确认'] = ''
        signin_ele['归还手牌按钮'] = ''
        signin_ele['归还手牌确定'] = ''
        signin_ele['历史明细'] = ''
        return signin_ele

    def remarkmanage_page(self):  # 租柜管理
        remarkmanage_ele = dict()
        remarkmanage_ele['柜子管理tab'] = ''
        remarkmanage_ele['添加柜子区域'] = ''
        remarkmanage_ele['区域名称'] = ''
        remarkmanage_ele['柜子数量'] = ''
        remarkmanage_ele['添加柜子区域确定'] = ''
        remarkmanage_ele['编辑柜子'] = ''
        remarkmanage_ele['编辑柜子区域名称'] = ''
        remarkmanage_ele['编辑柜子保存'] = ''
        remarkmanage_ele['柜子选择1号'] = ''
        remarkmanage_ele['手牌号输入框'] = ''
        remarkmanage_ele['柜子删除'] = ''
        remarkmanage_ele['柜子删除确定'] = ''
        remarkmanage_ele['柜子租还tab'] = ''
        remarkmanage_ele['柜子租还选择1号'] = ''
        remarkmanage_ele['选择客户输入框'] = ''
        remarkmanage_ele['租借备注输入框'] = ''
        remarkmanage_ele['柜子租借确定'] = ''
        remarkmanage_ele['柜子续费按钮'] = ''
        remarkmanage_ele['柜子续费结束时间输入框'] = ''
        remarkmanage_ele['柜子续费结束时间确定'] = ''
        remarkmanage_ele['柜子续费确定'] = ''
        remarkmanage_ele['柜子归还按钮'] = ''
        remarkmanage_ele['柜子归还备注输入框'] = ''
        remarkmanage_ele['柜子归还确定'] = ''
        remarkmanage_ele['柜子禁用按钮'] = ''
        remarkmanage_ele['柜子禁用备注输入框'] = ''
        remarkmanage_ele['柜子禁用确定'] = ''
        return remarkmanage_ele

    def viphanding_page(self):  # 会员办理
        viphanding_ele = dict()
        viphanding_ele['自动生成按钮'] = ''
        viphanding_ele['赠送时长'] = ''
        viphanding_ele['实付金额'] = ''
        viphanding_ele['备注'] = ''
        viphanding_ele['手机号输入框'] = ''
        viphanding_ele['手机号搜索图标'] = ''
        viphanding_ele['办理确定'] = ''
        viphanding_ele['定时开卡按钮'] = ''
        viphanding_ele['开卡日期输入'] = ''
        viphanding_ele['切换次卡选择'] = ''
        viphanding_ele['切换次卡选择次卡'] = ''
        viphanding_ele['切换次卡选择次卡名称'] = ''
        return viphanding_ele

    def vipcardmanage_page(self):  # 会员卡管理
        vipcardmanage_ele = dict()
        vipcardmanage_ele['时效卡更多'] = '//*[@id="pane-1-4-1"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[16]/div/div/button'
        vipcardmanage_ele['时效卡编辑'] = '/html/body/ul/li[4]'
        vipcardmanage_ele['时效卡编辑备注'] = '//*[@class="dialog-body-two"]/form/div[8]/div/div/textarea'
        vipcardmanage_ele['时效卡编辑确定'] = '//*[@class="dialog-body-two"]/form/div[9]/div/button'
        vipcardmanage_ele['时效卡续卡'] = '/html/body/ul/li[3]'
        vipcardmanage_ele['增加天数'] = '//*[@class="dialog-body-two"]/form/div[1]/div[2]/div/span/div/input'
        vipcardmanage_ele['时效卡续卡确定'] = '//*[@class="dialog-body-two"]/form/div[6]/div/button'
        vipcardmanage_ele['时效卡转卡'] = '/html/body/ul/li[2]'
        vipcardmanage_ele['时效卡转卡实付金额'] = '//*[@class="vipCard-infor"]/form/div/div/div/input'
        vipcardmanage_ele['时效卡转卡-手机号'] = '//*[@class="vipCard-infor"]/div/div/input'
        vipcardmanage_ele['时效卡转卡-搜索图标'] = '//*[@class="vipCard-infor"]/div[1]/div/div[2]/button'
        vipcardmanage_ele['时效卡转卡确定'] = '//*[@class="skryxi-bottom"]/button[2]'
        vipcardmanage_ele['时效卡停卡'] = '/html/body/ul/li[1]'
        vipcardmanage_ele['停卡开始日期'] = '//*[@class="dialog-body-two"]/form/div[1]/div/div/input[1]'
        vipcardmanage_ele['停卡结束日期'] = '//*[@class="dialog-body-two"]/form/div[1]/div/div/input[2]'
        vipcardmanage_ele['时效卡停卡实付金额'] = '//*[@class="dialog-body-two"]/form/div[2]/div/div/input'
        vipcardmanage_ele['时效卡停卡确定'] = '//*[@class="dialog-body-two"]/form/div[6]/div/button'
        vipcardmanage_ele['时效卡删除'] = '/html/body/ul/li[5]'
        vipcardmanage_ele['时效卡删除确定'] = '//*[@id="pane-1-4-1"]/div/div[10]/div/div[3]/span/button'
        vipcardmanage_ele['时效卡未开卡tab'] = '//*[@id="pane-1-4-1"]/div/div[1]/span/div[5]'
        vipcardmanage_ele['时效卡未开卡-开卡'] = '//*[@id="pane-1-4-1"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[16]/div/button[2]'
        vipcardmanage_ele['时效卡未开卡-开卡确定'] = '/html/body/div[3]/div/div[3]/button[2]'
        vipcardmanage_ele['时效卡回收站tab'] = '//*[@id="pane-1-4-1"]/div/div[1]/span/div[8]'
        vipcardmanage_ele['时效卡回收站-更多'] = '//*[@id="pane-1-4-1"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[16]/div/div/button'
        vipcardmanage_ele['时效卡回收站-恢复'] = '/html/body/ul/li[1]'
        vipcardmanage_ele['时效卡回收站-恢复确定'] = '//*[@id="pane-1-4-1"]/div/div[11]/div/div[3]/span/button'
        vipcardmanage_ele['时效卡回收站-删除'] = '/html/body/ul/li[2]'
        vipcardmanage_ele['时效卡回收站-删除确定'] = '//*[@id="pane-1-4-1"]/div/div[12]/div/div[3]/span/button'
        vipcardmanage_ele['次卡tab'] = '//*[@id="tab-1-4-2"]'
        vipcardmanage_ele['次卡更多'] = '//*[@id="pane-1-4-2"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[15]/div/div/button'
        vipcardmanage_ele['次卡编辑'] = '/html/body/ul/li[4]'
        vipcardmanage_ele['次卡编辑备注'] = '/html/body/div[3]/div/div[2]/div/div[2]/form/div[8]/div/div/textarea'
        vipcardmanage_ele['次卡编辑确定'] = '/html/body/div[3]/div/div[2]/div/div[2]/form/div[9]/div/button'
        vipcardmanage_ele['次卡续卡'] = '/html/body/ul/li[3]'
        vipcardmanage_ele['次卡续卡增加次数'] = '/html/body/div[3]/div/div[2]/div/div[2]/form/div[1]/div[1]/div/span/div/input'
        vipcardmanage_ele['次卡续卡确定'] = '/html/body/div[3]/div/div[2]/div/div[2]/form/div[6]/div/button'
        vipcardmanage_ele['次卡扣次'] = '/html/body/ul/li[1]'
        vipcardmanage_ele['次卡扣次确定'] = '/html/body/div[3]/div/div[2]/div/div[2]/form/div[3]/div/button'
        vipcardmanage_ele['次卡转卡'] = '/html/body/ul/li[2]'
        vipcardmanage_ele['次卡转卡实付金额'] = '/html/body/div[3]/div/div[2]/div/div/div[1]/div/form/div[1]/div/div/input'
        vipcardmanage_ele['次卡转卡-手机号'] = '/html/body/div[3]/div/div[2]/div/div/div[2]/div/div[1]/div/input'
        vipcardmanage_ele['次卡转卡-搜索图标'] = '/html/body/div[3]/div/div[2]/div/div/div[2]/div/div[1]/div/div[2]/button'
        vipcardmanage_ele['次卡转卡确定'] = '/html/body/div[3]/div/div[2]/div/div/div[2]/div/div[3]/button[2]'
        vipcardmanage_ele['次卡删除'] = '/html/body/ul/li[5]'
        vipcardmanage_ele['次卡删除确定'] = '//*[@id="pane-1-4-2"]/div/div[10]/div/div[3]/span/button'
        vipcardmanage_ele['次卡未开卡tab'] = '//*[@id="pane-1-4-2"]/div/div[1]/span/div[5]'
        vipcardmanage_ele['次卡未开卡-开卡'] = '//*[@id="pane-1-4-2"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[15]/div/button[2]'
        vipcardmanage_ele['次卡未开卡-开卡确定'] = '/html/body/div[3]/div/div[3]/button[2]/span'
        vipcardmanage_ele['次卡回收站tab'] = '//*[@id="pane-1-4-2"]/div/div[1]/span/div[6]'
        vipcardmanage_ele['次卡回收站-更多'] = '//*[@id="pane-1-4-2"]/div/div[3]/div[4]/div[2]/table/tbody/tr/td[15]/div/div/button'
        vipcardmanage_ele['次卡回收站-恢复'] = '/html/body/ul/li[1]'
        vipcardmanage_ele['次卡回收站-恢复确定'] = '//*[@id="pane-1-4-2"]/div/div[11]/div/div[3]/span/button'
        vipcardmanage_ele['次卡回收站-删除'] = '/html/body/ul/li[2]'
        vipcardmanage_ele['次卡回收站-删除确定'] = '//*[@id="pane-1-4-2"]/div/div[12]/div/div[3]/span/button'
        return vipcardmanage_ele

    def cashier_page(self):  # 收银台
        cashier_ele = dict()
        cashier_ele['商品管理tab'] = '//*[@id="tab-1-5-4"]'
        cashier_ele['添加商品'] = '//*[@id="pane-1-5-4"]/div/div[1]/div/button'
        cashier_ele['商品条码'] = '//*[@id="pane-1-5-4"]/div/div[6]/div/div[2]/div/form/div[1]/div/div/input'
        cashier_ele['商品名称'] = '//*[@id="pane-1-5-4"]/div/div[6]/div/div[2]/div/form/div[2]/div/div/input'
        cashier_ele['出售单价'] = '//*[@id="pane-1-5-4"]/div/div[6]/div/div[2]/div/form/div[3]/div/div/input'
        cashier_ele['添加商品确定'] = '//*[@id="pane-1-5-4"]/div/div[6]/div/div[2]/div/div/button[2]'
        cashier_ele['编辑商品'] = '//*[@id="pane-1-5-4"]/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[8]/div/button[2]'
        cashier_ele['编辑商品商品单价'] = '/html/body/div[2]/div/div[2]/form/div[3]/div/div/input'
        cashier_ele['编辑商品确定'] = '/html/body/div[2]/div/div[2]/div/span/button[2]'
        cashier_ele['入库商品'] = '//*[@id="pane-1-5-4"]/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[8]/div/button[1]'
        cashier_ele['下一步1'] = '//*[@id="pane-1-5-4"]/div/div[6]/div/div[2]/div/div/div[2]/div/button'
        cashier_ele['入库商品确定入库'] = '//*[@id="pane-1-5-4"]/div/div[6]/div/div[2]/div/div/div[2]/div/button[2]'
        cashier_ele['入库记录tab'] = '//*[@id="tab-1-5-2"]'
        cashier_ele['商品入库按钮'] = '//*[@id="pane-1-5-2"]/div/div[1]/div/button'
        cashier_ele['商品条码输入框'] = '//*[@id="pane-1-5-2"]/div/div[6]/div/div[2]/div/div/div[2]/div/input'
        cashier_ele['商品条码搜索图标'] = '//*[@id="pane-1-5-2"]/div/div[6]/div/div[2]/div/div/div[2]/div/div[2]/button'
        cashier_ele['下一步2'] = '//*[@id="pane-1-5-2"]/div/div[6]/div/div[2]/div/div/div[2]/div/button[2]'
        cashier_ele['确认入库按钮'] = '//*[@id="pane-1-5-2"]/div/div[6]/div/div[2]/div/div/div[2]/div/button[2]'
        cashier_ele['快速购物tab'] = '//*[@id="tab-1-5-1"]'
        cashier_ele['购物商品条码输入框'] = '//*[@id="pane-1-5-1"]/div/div[1]/div/div/div/input'
        cashier_ele['购物商品条码搜索图标'] = '//*[@id="pane-1-5-1"]/div/div[1]/div/div/div/div[2]/button'
        cashier_ele['现金'] = '//*[@id="pane-1-5-1"]/div/div[2]/div[1]/ul/li[1]'
        cashier_ele['确认收款'] = '//*[@id="pane-1-5-1"]/div/div[4]/div/div[2]/div[3]/span/button'
        return cashier_ele

    def membership_manage(self):  # 客户管理
        membership_ele = dict()
        membership_ele['潜在客户tab'] = '//*[@id="tab-2-1-3"]'
        membership_ele['潜客登记'] = '//*[@id="pane-2-1-3"]/div/div[2]/div/button'
        membership_ele['姓名'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[1]/div/div/div/input'
        membership_ele['性别选择'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[3]/div/div/div/div[1]/span/span/i'
        membership_ele['性别选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        membership_ele['手机号'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[5]/div/div/div[1]/input'
        membership_ele['会籍选择'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[7]/div/div/div/div[1]/span/span/i'
        membership_ele['会籍选择确定'] = '/html/body/div[4]/div[1]/div[1]/ul/li[1]'
        membership_ele['来源选择'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[2]/div/div/div/div[1]/span/span/i'
        membership_ele['来源选择确定'] = '/html/body/div[5]/div[1]/div[1]/ul/li[1]'
        membership_ele['意向选择'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[4]/div/div/div/div[1]/span/span/i'
        membership_ele['意向选择确定'] = '/html/body/div[6]/div[1]/div[1]/ul/li[1]'
        membership_ele['目的选择'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[6]/div/div/div/div[1]/span/span/i'
        membership_ele['目的选择确定'] = '/html/body/div[7]/div[1]/div[1]/ul/li[1]'
        membership_ele['备注'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[2]/div/form/div[8]/div/div/div/input'
        membership_ele['潜客登记提交按钮'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[3]/span/button'
        membership_ele['潜客更多'] = '//*[@id="pane-2-1-3"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[19]/div/div/button'
        membership_ele['潜客编辑'] = '/html/body/ul/li[1]'
        membership_ele['潜客编辑生日'] = '//*[@id="pane-2-1-3"]/div/div[5]/div/div[2]/div[1]/div/div/div[1]/form/div[3]/div/div/input'
        membership_ele['潜客编辑确定'] = '//*[@id="pane-2-1-3"]/div/div[5]/div/div[2]/div[3]/button'
        membership_ele['潜客分配会籍'] = '/html/body/ul/li[2]'
        membership_ele['分配会籍选择'] = '//*[@id="pane-2-1-3"]/div/div[5]/div/div[2]/div[1]/form/div/div/div/div[1]/span/span/i'
        membership_ele['分配会籍选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        membership_ele['潜客分配会籍确定按钮'] = '//*[@id="pane-2-1-3"]/div/div[5]/div/div[2]/div[2]/button'
        membership_ele['潜客分配教练'] = '/html/body/ul/li[3]'
        membership_ele['分配教练选择'] = '//*[@id="pane-2-1-3"]/div/div[5]/div/div[2]/div[1]/form/div/div/div/div[1]/span/span/i'
        membership_ele['分配教练选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        membership_ele['潜客分配教练确定按钮'] = '//*[@id="pane-2-1-3"]/div/div[5]/div/div[2]/div[2]/button'
        membership_ele['潜客删除'] = '/html/body/ul/li[4]'
        membership_ele['潜客删除确定'] = '//*[@id="pane-2-1-3"]/div/div[7]/div/div[3]/span/button'
        membership_ele['潜客回收站tab'] = '//*[@id="pane-2-1-3"]/div/div[1]/span/div[7]'
        membership_ele['潜客恢复'] = '//*[@id="pane-2-1-3"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[19]/div/button'
        membership_ele['潜客恢复确定'] = '//*[@id="pane-2-1-3"]/div/div[8]/div/div[3]/span/button'
        membership_ele['会员管理tab'] = '//*[@id="tab-2-1-1"]'
        membership_ele['会员管理更多'] = '//*[@id="pane-2-1-1"]/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[17]/div/div/button'
        membership_ele['会员管理编辑'] = '/html/body/ul/li[3]'
        membership_ele['会员管理编辑生日'] = '//*[@id="pane-2-1-1"]/div/div[6]/div/div[2]/div[1]/div/div/div[1]/form/div[3]/div/div/input'
        membership_ele['会员管理编辑确定'] = '//*[@id="pane-2-1-1"]/div/div[6]/div/div[2]/div[3]/button'
        membership_ele['会员管理分配会籍'] = '/html/body/ul/li[1]'
        membership_ele['分配会籍-选择'] = '//*[@id="pane-2-1-1"]/div/div[6]/div/div[2]/div[1]/form/div/div/div/div[1]/span/span/i'
        membership_ele['分配会籍-选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        membership_ele['会员管理分配会籍确定按钮'] = '//*[@id="pane-2-1-1"]/div/div[6]/div/div[2]/div[2]/button'
        membership_ele['会员管理分配教练'] = '/html/body/ul/li[2]'
        membership_ele['分配教练-选择'] = '//*[@id="pane-2-1-1"]/div/div[6]/div/div[2]/div[1]/form/div/div/div/div[1]/span/span/i'
        membership_ele['分配教练-选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        membership_ele['会员管理分配教练确定按钮'] = '//*[@id="pane-2-1-1"]/div/div[6]/div/div[2]/div[2]/button'
        membership_ele['会员管理删除'] = '/html/body/ul/li[4]'
        membership_ele['会员管理删除确定'] = '//*[@id="pane-2-1-1"]/div/div[8]/div/div[3]/span/button'
        return membership_ele

    def perclass_manage(self):  # 私教课程
        perclass_ele = dict()
        perclass_ele['添加私教课按钮'] = '//*[@id="tab-0"]/div/button[1]'
        perclass_ele['课程名称输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[1]/div/div/input'
        perclass_ele['课程类型选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[2]/div/div/div[1]/span/span/i'
        perclass_ele['课程类型选择确定按钮'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'  # div3
        perclass_ele['课程时长选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[3]/div/div/div[1]/span/span/i'
        perclass_ele['课程时长选择确定按钮'] = '/html/body/div[4]/div[1]/div[1]/ul/li[1]'  # div4
        perclass_ele['课程介绍输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[5]/div/div/textarea'
        perclass_ele['课程图片选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[6]/div/div[2]/div[1]/div[1]/span/span/i'
        perclass_ele['课程图片选择确定按钮'] = '/html/body/div[5]/div[1]/div[1]/ul/li[1]'  # div5
        perclass_ele['添加私教课确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[3]/span/button'
        perclass_ele['编辑私教课按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div[2]/button'
        perclass_ele['编辑私教课课程名输入框'] = '//*[@class="el-tabs el-tabs--card el-tabs--left"]/div[2]/div[3]/div[1]/div[1]/form/div[1]/div/div[2]/input'
        perclass_ele['编辑私教课按钮保存按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div[2]/button'
        perclass_ele['删除私教课按钮'] = '//*[@id="tab-0"]/div/button[2]'
        perclass_ele['删除私教课确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[6]/div/div[3]/span/button'
        perclass_ele['添加私教课教练按钮'] = '//*[@class="table-box"]/div[2]/button'
        perclass_ele['添加私教课教练课程单价输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[2]/div/div/input'
        perclass_ele['添加私教课教练带课教练选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[3]/div/div/div[1]/span/span/i'
        perclass_ele['添加私教课教练带课教练选择确定按钮'] = '/html/body/div[6]/div[1]/div[1]/ul/li[1]'
        perclass_ele['添加私教课教练确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[3]/span/button'
        perclass_ele['编辑私教课带课教练按钮'] = '//*[@class="el-table__fixed-right"]/div[2]/table/tbody/tr[1]/td[9]/div/button[2]'
        perclass_ele['编辑私教课带课教练课程单价输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/form/div[3]/div/div/input'
        perclass_ele['编辑私教课带课教练确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[3]/span/button'
        perclass_ele['删除私教课带课教练按钮'] = '//*[@class="el-table__fixed-right"]/div[2]/table/tbody/tr[1]/td[9]/div/button[3]'
        perclass_ele['删除私教课带课教练确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[3]/span/button'
        perclass_ele['私教课购买按钮'] = '//*[@class="el-table__fixed-right"]/div[2]/table/tbody/tr[1]/td[9]/div/button[1]'
        perclass_ele['失效日期输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/div[2]/form[2]/div[2]/div/div/input'
        perclass_ele['实付金额输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/div[2]/form[2]/div[3]/div/div/input'
        perclass_ele['购买备注输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/div[2]/form[1]/div[5]/div/div/input'
        perclass_ele['下一步按钮1'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[3]/span/button'
        perclass_ele['会员手机输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[8]/div/div[2]/div[2]/div[2]/input'
        perclass_ele['会员手机搜索按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[8]/div/div[2]/div[2]/div[2]/div/button'
        perclass_ele['私教课购买确认购买按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[9]/div/div[3]/span/button[2]'
        return perclass_ele

    def perclassbuy_manage(self):  # 私教购买
        perclassbuy_ele = dict()
        perclassbuy_ele['添加购买按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div/button'
        perclassbuy_ele['课程名称选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[2]/form[1]/div[1]/div/div/div[1]/span/span/i'
        perclassbuy_ele['课程名称选择确定按钮'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        perclassbuy_ele['教练姓名选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[2]/form[2]/div[1]/div/div/div[1]/span/span/i'
        perclassbuy_ele['教练姓名选择确定按钮'] = '/html/body/div[4]/div[1]/div[1]/ul/li'
        perclassbuy_ele['失效日期输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[2]/form[2]/div[2]/div/div/input'
        perclassbuy_ele['实付金额输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[2]/form[2]/div[3]/div/div/input'
        perclassbuy_ele['购买备注输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[2]/form[1]/div[5]/div/div/input'
        perclassbuy_ele['下一步按钮1'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[3]/span/button'
        perclassbuy_ele['会员手机输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div[2]/div[2]/input'
        perclassbuy_ele['会员手机搜索按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div[2]/div[2]/div/button'
        perclassbuy_ele['私教购买确定购买按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[6]/div/div[3]/span/button[2]'
        perclassbuy_ele['编辑私教购买信息按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[18]/div/button[1]'
        perclassbuy_ele['编辑私教购买信息购买备注输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/div/form/div[3]/div/div/textarea'
        perclassbuy_ele['编辑私教购买信息确认修改按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[3]/span/button'
        perclassbuy_ele['删除私教购买信息按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[18]/div/button[3]'
        perclassbuy_ele['删除私教购买信息确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[9]/div/div[3]/span/button'
        return perclassbuy_ele

    def perclassorder_manage(self):  # 私教预约
        perclassorder_ele = dict()
        perclassorder_ele['添加预约按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/button'
        perclassorder_ele['会员手机号输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div[1]/div/input'
        perclassorder_ele['会员手机号搜索按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div[1]/div/div[2]/button'
        perclassorder_ele['上课时间选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div[2]/span[2]/ul/li[25]'
        perclassorder_ele['确认预约按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div[3]/span/button'
        perclassorder_ele['取消预约按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[18]/div/button[1]'
        perclassorder_ele['取消预约确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[3]/span/button'
        perclassorder_ele['消课按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div[4]/div[2]/table/tbody/tr[2]/td[18]/div/button'
        perclassorder_ele['确认无误，开始消课按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[6]/div[1]/div/div[2]/div[2]/span/button'
        perclassorder_ele['消课取消按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[6]/div[2]/div/div[1]/button/i'
        return perclassorder_ele

    def groupclass_manage(self):  # 团课管理
        groupclass_ele = dict()
        groupclass_ele['团课课程tab'] = '//*[@id="tab-3-4-2"]'
        groupclass_ele['添加课程按钮'] = '//*[@id="pane-3-4-2"]/div/div[1]/button'
        groupclass_ele['课程类型选择'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[1]/div/div/div[1]/span/span/i'
        groupclass_ele['课程类型选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        groupclass_ele['教练姓名选择'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[3]/div/div/div[1]/span/span/i'
        groupclass_ele['教练姓名选择确定'] = '/html/body/div[4]/div[1]/div[1]/ul/li[1]'
        groupclass_ele['课程名称输入框'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[2]/div/div/input'
        groupclass_ele['课程价格输入框'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[4]/div/div/input'
        groupclass_ele['上课地点'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[5]/div/div/input'
        groupclass_ele['最少人数'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[6]/div/div/input'
        groupclass_ele['最多人数'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[1]/form/div[7]/div/div/input'
        groupclass_ele['添加课程确定按钮'] = '//*[@id="pane-3-4-2"]/div/div[4]/div/div[2]/div[2]/span/button'
        groupclass_ele['编辑课程'] = '//*[@id="pane-3-4-2"]/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[10]/div/span[1]'
        groupclass_ele['编辑课程课程名称输入框'] = '//*[@id="pane-3-4-2"]/div/div[6]/div/div[2]/div[1]/form/div[2]/div/div/input'
        groupclass_ele['编辑课程确定'] = '//*[@id="pane-3-4-2"]/div/div[6]/div/div[2]/div[2]/span/button'
        groupclass_ele['删除课程'] = '//*[@id="pane-3-4-2"]/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[10]/div/span[3]'
        groupclass_ele['删除课程确定'] = '//*[@id="pane-3-4-2"]/div/div[6]/div/div[3]/span/button'
        groupclass_ele['排期'] = '//*[@id="pane-3-4-2"]/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[10]/div/span[2]'
        groupclass_ele['开始日期'] = '//*[@id="pane-3-4-2"]/div/div[5]/div/div[2]/div/div[3]/div/input[1]'
        groupclass_ele['结束日期'] = '//*[@id="pane-3-4-2"]/div/div[5]/div/div[2]/div/div[3]/div/input[2]'
        groupclass_ele['团课课程排期周日选择'] = '//*[@id="pane-3-4-2"]/div/div[5]/div/div[2]/div/div[4]/div/label[7]/span[1]/span'
        groupclass_ele['开始时间'] = '//*[@id="pane-3-4-2"]/div/div[5]/div/div[2]/div/div[5]/div/div[3]/table/tbody/tr/td[2]/div/div/input'
        groupclass_ele['结束时间'] = '//*[@id="pane-3-4-2"]/div/div[5]/div/div[2]/div/div[5]/div/div[3]/table/tbody/tr/td[3]/div/div/input'
        groupclass_ele['排期确定'] = '//*[@id="pane-3-4-2"]/div/div[5]/div/div[3]/span/button'
        groupclass_ele['课程排期tab'] = '//*[@id="tab-3-4-1"]'
        groupclass_ele['添加排期'] = '//*[@id="pane-3-4-1"]/div/div[1]/button[1]'
        groupclass_ele['添加已有课程tab'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[1]/div[1]/label[2]/span[1]/span'
        groupclass_ele['课程选择'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[1]/div[2]/div[1]/span/span/i'
        groupclass_ele['课程选择确定'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        groupclass_ele['添加排期开始日期'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[3]/div/input[1]'
        groupclass_ele['添加排期结束日期'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[3]/div/input[2]'
        groupclass_ele['添加排期周日选择'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[4]/div/label[7]/span[1]/span'
        groupclass_ele['添加排期开始时间'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[5]/div/div[3]/table/tbody/tr/td[2]/div/div/input'
        groupclass_ele['添加排期结束时间'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[2]/div/div[5]/div/div[3]/table/tbody/tr/td[3]/div/div/input'
        groupclass_ele['添加排期确定'] = '//*[@id="pane-3-4-1"]/div/div[3]/div/div[3]/span/button'
        groupclass_ele['周日选择'] = '//*[@id="pane-3-4-1"]/div/table/tbody/tr/td[7]/div/div/div'
        groupclass_ele['编辑排期'] = '//*[@id="pane-3-4-1"]/div/div[1]/button[2]'
        groupclass_ele['编辑排期结束时间'] = '//*[@id="pane-3-4-1"]/div/div[4]/div/div[2]/div/div[3]/div[3]/input'
        groupclass_ele['编辑排期确定'] = '//*[@id="pane-3-4-1"]/div/div[4]/div/div[3]/span/button'
        groupclass_ele['删除排期'] = '//*[@id="pane-3-4-1"]/div/div[1]/button[3]'
        groupclass_ele['删除排期确定'] = '//*[@id="pane-3-4-1"]/div/div[6]/div/div[3]/span/button'
        groupclass_ele['预约课程'] = '//*[@id="pane-3-4-1"]/div/div[1]/button[4]'
        groupclass_ele['实付金额'] = '//*[@id="pane-3-4-1"]/div/div[5]/div/div/div[2]/div/div[2]/form/div[6]/div/div/input'
        groupclass_ele['下一步1'] = '//*[@id="pane-3-4-1"]/div/div[5]/div/div/div[2]/div/div[3]/span/button'
        groupclass_ele['会员手机号'] = '//*[@id="pane-3-4-1"]/div/div[5]/div/div/div[2]/div/div[2]/div[2]/input'
        groupclass_ele['搜索图标'] = '//*[@id="pane-3-4-1"]/div/div[5]/div/div/div[2]/div/div[2]/div[2]/div/button'
        groupclass_ele['确认预约按钮'] = '//*[@id="pane-3-4-1"]/div/div[5]/div/div/div[2]/div/div[3]/span/button[2]'
        groupclass_ele['查看预约'] = '//*[@id="pane-3-4-1"]/div/div[1]/button[5]'
        groupclass_ele['取消预约'] = '//*[@id="pane-3-4-1"]/div/div[5]/div/div[2]/div[2]/div[3]/table/tbody/tr[1]/td[17]/div/span[2]'
        groupclass_ele['取消预约确定'] = '//*[@class="el-dialog"]/div[3]/span/button'  # 难搞，相对位置也不行
        groupclass_ele['打印课表'] = '//*[@id="pane-3-4-1"]/div/div[1]/button[6]'
        return groupclass_ele

    def openclass_manage(self):  # 公开课管理
        openclass_ele = dict()
        openclass_ele['添加公开课按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/button[1]'
        openclass_ele['课程名称输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[1]/div/div/input'
        openclass_ele['教练姓名选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[2]/div/div/div[1]/span/span/i'
        openclass_ele['教练姓名选择确认按钮'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        openclass_ele['上课地点输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[3]/div/div/input'
        openclass_ele['上课人数最小输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[4]/div/div/input'
        openclass_ele['上课人数最大输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[5]/div/div/input'
        openclass_ele['上课时间选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[6]/div/div[1]/div[1]/span/span/i'
        openclass_ele['周一选择确定按钮'] = '/html/body/div[4]/div[1]/div[1]/ul/li[1]'
        openclass_ele['上课开始时间输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[6]/div/div[2]/input[1]'
        openclass_ele['上课结束时间输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[1]/form/div[6]/div/div[2]/input[2]'
        openclass_ele['上课时间确定按钮'] = '//div[@class="el-time-panel__footer"]/button[2]'
        openclass_ele['添加公开课确认按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div/div[2]/div[2]/span/button'
        openclass_ele['选择周一课程'] = '//*[@id="app"]/div/div[2]/section/div/table/tbody/tr/td[1]/div/div/div/div[1]'
        openclass_ele['编辑课程按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/button[2]'
        openclass_ele['编辑课程确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[2]/span/button'
        openclass_ele['编辑课程课程名称输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/div[1]/form/div[1]/div/div/input'
        openclass_ele['删除公开课按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/button[3]'
        openclass_ele['删除公开课确认按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[3]/span'
        openclass_ele['打印课表'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/button[4]'
        return openclass_ele

    def sidereport_manage(self):  # 体侧报告
        sidereport_ele = dict()
        sidereport_ele['体侧录入按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/button'
        sidereport_ele['会员手机号输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/div[1]/input'
        sidereport_ele['会员手机号搜索按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/div[1]/div[2]/button'
        sidereport_ele['下一步按钮1'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/div/button[2]'
        sidereport_ele['体侧时间输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[1]/div[1]/div/div/div/input'
        sidereport_ele['体侧时间确定按钮'] = '/html/body/div[3]/div[2]/button[2]'
        sidereport_ele['年龄'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[1]/div[2]/div/div/div/input'
        sidereport_ele['身高'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[2]/div[1]/div/div/div/input'
        sidereport_ele['体重'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[2]/div[2]/div/div/div/input'
        sidereport_ele['蛋白质'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[3]/div[1]/div/div/div/input'
        sidereport_ele['基础代谢'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[3]/div[2]/div/div/div/input'
        sidereport_ele['水分'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[4]/div[1]/div/div/div/input'
        sidereport_ele['体脂率'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[4]/div[2]/div/div/div/input'
        sidereport_ele['内脏脂肪'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[5]/div[1]/div/div/div/input'
        sidereport_ele['骨量'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[5]/div[2]/div/div/div/input'
        sidereport_ele['皮下脂肪'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[6]/div[1]/div/div/div/input'
        sidereport_ele['骨骼肌'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[6]/div[2]/div/div/div/input'
        sidereport_ele['静态心率'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[7]/div[1]/div/div/div/input'
        sidereport_ele['腰臀比'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/form/div[7]/div[2]/div/div/div/input'
        sidereport_ele['体侧录入确认按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/div[2]/div/button[2]'
        sidereport_ele['编辑按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[14]/div/button[1]'
        sidereport_ele['编辑年龄输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/form/div[1]/div[2]/div/div/div/input'
        sidereport_ele['编辑保存按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/div/div/button[2]'
        sidereport_ele['删除按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[14]/div/button[2]'
        sidereport_ele['删除确认按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[6]/div/div[3]/span/button'
        sidereport_ele['查看按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[3]/div[4]/div[2]/table/tbody/tr[1]/td[14]/div/div/button'
        sidereport_ele['app查看'] = '/html/body/ul/li[1]'
        sidereport_ele['app查看关闭按钮'] = '/html/body/div[3]/div/div[1]/button/i'
        sidereport_ele['pc查看'] = '/html/body/ul/li[2]'
        return sidereport_ele

    def staff_manage(self):  # 员工管理
        staff_ele = dict()
        staff_ele['添加员工按钮'] = '//*[@class="filter-container"]/button'
        staff_ele['姓名输入框'] = '//*[@class="el-input el-input--medium"]/input'
        staff_ele['角色选择按钮'] = '//*[@class="el-form ruleForm"]/div[2]/div/div/div/span/span/i'
        staff_ele['角色选择确定按钮'] = '/html/body/div[3]/div[1]/div[1]/ul/li[1]'
        staff_ele['上传员工头像按钮'] = '//*[@id="takePicture"]/div[1]/div/div[2]/a[1]'
        staff_ele['上传员工头像弹出按钮'] = '//*[@id="takePicture"]/div[2]/div/div[2]/div[1]'
        staff_ele['上传员工头像保存按钮'] = '//*[@id="takePicture"]/div[2]/div/div[2]/div[2]/a[2]'
        staff_ele['添加员工提交按钮'] = '//*[@class="dialog-footer"]/button'
        staff_ele['禁用员工按钮'] = '//*[@class="el-table__fixed-body-wrapper"]/table/tbody/tr[1]/td[12]/div/button[2]'
        staff_ele['禁用员工确定按钮'] = '//*[@class="dialog-footer"]/button[2]'
        staff_ele['员工编辑按钮'] = '//*[@class="el-table__fixed-body-wrapper"]/table/tbody/tr[1]/td[12]/div/button[1]'
        staff_ele['员工编辑姓名输入框'] = '//*[@class="el-input el-input--medium"]/input'
        staff_ele['员工编辑提交按钮'] = '//*[@class="dialog-footer"]/button'
        staff_ele['切换到禁用table'] = '//*[@class="boxser"]/span/div[2]'
        staff_ele['启用员工按钮'] = '//*[@class="el-table__fixed-body-wrapper"]/table/tbody/tr[1]/td[12]/div/button[2]'
        staff_ele['启用员工确定按钮'] = '//*[@class="dialog-footer"]/button[2]'
        return staff_ele

    def cardKind_manage(self):  # 卡种管理
        cardKind_ele = dict()
        cardKind_ele['添加卡种按钮'] = '//*[@class="filter-container"]/button'
        cardKind_ele['卡种名称输入框'] = '//*[@class="el-input el-input--medium"]/input'
        cardKind_ele['卡种封面选择按钮'] = '//*[@class="el-form-item is-required el-form-item--medium"]/div/div/div/div/span/span/i'
        cardKind_ele['卡种封面确定按钮'] = '/html/body/div[3]/div[1]/div[1]/ul/li[2]'
        cardKind_ele['时效卡天数输入框'] = '//*[@class="el-form-item is-required el-form-item--medium"]/div/span/div/input'
        cardKind_ele['底价输入框'] = '//*[@class="el-form-item is-required el-form-item--medium"]/div/div/input'
        cardKind_ele['价格输入框'] = '//*[@class="el-row"]/div[2]/div/div/div/input'
        cardKind_ele['SAAS上架选择按钮'] = '//*[@class="el-row"]/div/div/div/div/div/span/span/i'
        cardKind_ele['SAAS上架确定按钮'] = '/html/body/div[4]/div[1]/div[1]/ul/li[2]'
        cardKind_ele['备注输入框'] = '//*[@class="el-textarea el-input--medium"]/textarea'
        cardKind_ele['添加卡种确定按钮'] = '//*[@class="dialog-footer"]/button'
        cardKind_ele['编辑卡种按钮'] = '//*[@class="el-table__fixed-body-wrapper"]/table/tbody/tr[1]/td[16]/div/button'
        cardKind_ele['编辑卡种更新按钮'] = '//*[@class="dialog-footer"]/button'
        cardKind_ele['卡种删除按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[16]/div/button[2]'
        cardKind_ele['卡种删除确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[3]/span/button'
        return cardKind_ele

    def role_manage(self):  # 角色管理
        role_ele = dict()
        role_ele['添加角色按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div/button'
        role_ele['角色名称输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/form/div[1]/div/input'
        role_ele['权限模板选择按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/form/div[2]/div/div[1]/span/span/i'
        role_ele['权限模板选择确定按钮'] = '/html/body/div[3]/div[1]/div[1]/ul/ul[2]/li[2]/ul/li[2]'
        role_ele['角色描述输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/form/div[3]/div/textarea'
        role_ele['添加角色确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[4]/div/div[2]/form/div[4]/span/button'
        role_ele['编辑角色按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[7]/div/button[2]'
        role_ele['编辑角色名称输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/form/div[1]/div/div/input'
        role_ele['编辑角色描述输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/form/div[2]/div/div/textarea'
        role_ele['编辑角色确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[7]/div/div[2]/form/div[3]/span/button'
        role_ele['权限分配按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[7]/div/button[1]'
        role_ele['权限分配确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/div/div[2]/button'
        role_ele['角色删除按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div[4]/div[2]/table/tbody/tr[1]/td[7]/div/button[3]'
        role_ele['删除确定按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[6]/div/div[3]/span/button'
        return role_ele

    def passage_manage(self):  # 文章推送
        passage_ele = dict()
        passage_ele['添加文章按钮'] = '//*[@id="pane-5-3-1"]/div/div[1]/div/button'
        passage_ele['文章名称输入框'] = '//*[@id="pane-5-3-1"]/div/div[4]/div/div[3]/div/form/div[1]/div/div/input'
        passage_ele['文章封面上传按钮'] = '//*[@id="aaa"]/div[1]/div/div[2]/a'
        passage_ele['文章封面上传弹窗按钮'] = '//*[@id="aaa"]/div[2]/div/div[2]/div[1]'
        passage_ele['文章封面保存按钮'] = '//*[@id="aaa"]/div[2]/div/div[2]/div[2]/a[2]'
        passage_ele['文章摘要输入框'] = '//*[@id="pane-5-3-1"]/div/div[4]/div/div[3]/div/form/div[2]/div[2]/div/textarea'
        passage_ele['文章摘要输入框iframe'] = 'ke-edit-iframe'  # class_name定位
        passage_ele['文章内容输入框'] = '/html/body'
        passage_ele['添加文章确定按钮'] = '//*[@id="pane-5-3-1"]/div/div[4]/div/div[3]/div/button[2]'
        passage_ele['删除文章按钮'] = '//*[@id="pane-5-3-1"]/div/div[2]/div/div/div[4]/div/i[4]'
        passage_ele['删除文章确定按钮'] = '//*[@id="pane-5-3-1"]/div/div[7]/div/div[2]/div[2]/span/button[2]'
        passage_ele['编辑文章按钮'] = '//*[@id="pane-5-3-1"]/div/div[2]/div/div/div[4]/div/i[1]'
        passage_ele['编辑文章提交按钮'] = '//*[@id="pane-5-3-1"]/div/div[4]/div/div[3]/div/button[2]'
        passage_ele['文章标题搜索输入框'] = '//*[@id="pane-5-3-1"]/div/div[1]/div/div[1]/div/input'
        passage_ele['文章标题搜索图标'] = '//*[@id="pane-5-3-1"]/div/div[1]/div/div[1]/div/div[2]/button'
        passage_ele['文章标题(列表第一个)'] = '//*[@id="pane-5-3-1"]/div/div[2]/div[1]/div/div[3]/p'
        return passage_ele

    def protocol_manage(self):  # 协议模板
        protocol_ele = dict()
        protocol_ele['编辑协议按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/button[2]'
        protocol_ele['编辑协议保存按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[5]/button[2]'
        protocol_ele['协议重置按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/button[3]'
        protocol_ele['手机号输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/div/div/input'
        protocol_ele['搜索图标'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/div/div/div[2]/button'
        protocol_ele['打印协议按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/button[1]'
        protocol_ele['切换私教协议tab'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div/div/div[1]/div/div[3]'
        return protocol_ele

    def club_manage(self):  # 俱乐部信息
        club_ele = dict()
        club_ele['修改俱乐部信息按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div[1]/div/div[1]/div/button[1]'
        club_ele['场馆名称输入框'] = '//*[@id="clearinpout"]'
        club_ele['场馆电话输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div[1]/div/div[2]/div[1]/div[3]/div/input'
        club_ele['场馆地址输入框'] = '//*[@id="address"]'
        club_ele['保存修改按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div[1]/div/div[1]/div/button[2]'
        club_ele['法人信息认证按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[1]/div[2]/div/div[6]/button'
        club_ele['账户名称输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/div[2]/div/div[2]/form/div[1]/div/div/input'
        club_ele['开户行-支行输入框'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/div[2]/div/div[2]/form/div[2]/div/div/input'
        club_ele['提交认证按钮'] = '//*[@id="app"]/div/div[2]/section/div/div[2]/div/div[3]/span/button'
        return club_ele

